#!/usr/bin/env python3
"""Insert or refresh a contents list in a summary's markdown.

    uv run python scripts/contents.py <slug> [--brief] [--depth 3] [--check]

The PDF gets a contents list with real page numbers at render time. The markdown gets nothing,
and a 25,000-word file of headings with no way to jump is the form most people actually read —
in an editor, on GitHub, grepped. This adds one, between the review header and the body.

Idempotent: the block is delimited, so re-running replaces it rather than stacking copies.
Run it after any revision that changes headings, or the contents silently describe an older
document — which is worse than having none, because a stale map is trusted.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import corpus  # noqa: E402

BEGIN = "<!-- contents: generated by scripts/contents.py — do not edit by hand -->"
END = "<!-- /contents -->"

_HEADING_RE = re.compile(r"^(#{2,6})\s+(.*?)\s*$")
_FENCE_RE = re.compile(r"^(```|~~~)")
_LOCATOR_RE = re.compile(r"\s*\[[^\]]*\]\s*$")


def slugify(text: str) -> str:
    """GitHub's anchor rules: lowercase, strip punctuation, spaces to hyphens."""
    s = re.sub(r"[`*_]", "", text).lower()
    s = re.sub(r"[^\w\s-]", "", s)
    return re.sub(r"\s+", "-", s.strip())


def headings(md: str, depth: int) -> list[tuple[int, str, str]]:
    """(level, title, anchor) for headings outside fenced blocks, deduplicating anchors."""
    out: list[tuple[int, str, str]] = []
    seen: dict[str, int] = {}
    in_fence = False
    for line in md.splitlines():
        if _FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence or not (m := _HEADING_RE.match(line)):
            continue
        level = len(m.group(1))
        if level > depth:
            continue
        title = m.group(2)
        anchor = slugify(title)
        # GitHub appends -1, -2 … to repeated anchors; mirror that or the links break.
        n = seen.get(anchor, 0)
        seen[anchor] = n + 1
        out.append((level, title, anchor if n == 0 else f"{anchor}-{n}"))
    return out


def render(items: list[tuple[int, str, str]]) -> str:
    lines = [BEGIN, "", "## Contents", ""]
    for level, title, anchor in items:
        if title.strip().lower() == "contents":
            continue
        # Strip a trailing locator: it belongs on the heading, not in a navigation list.
        clean = _LOCATOR_RE.sub("", title)
        lines.append(f"{'  ' * (level - 2)}- [{clean}](#{anchor})")
    lines += ["", END]
    return "\n".join(lines)


def splice(md: str, block: str) -> str:
    """Replace an existing block, or insert after the front matter's `---` rule."""
    if BEGIN in md and END in md:
        head, rest = md.split(BEGIN, 1)
        return head + block + rest.split(END, 1)[1]
    parts = md.split("\n---\n", 1)
    if len(parts) == 2:
        return parts[0] + "\n---\n\n" + block + "\n" + parts[1]
    return block + "\n\n" + md  # no front matter; put it at the top


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("slug")
    ap.add_argument("--brief", action="store_true", help="the brief instead of the deep summary")
    ap.add_argument("--depth", type=int, default=3, help="deepest heading level to list")
    ap.add_argument("--check", action="store_true", help="report staleness, change nothing")
    args = ap.parse_args()

    book = corpus.load(args.slug)
    path = book.brief_path if args.brief else book.deep_path
    if not path.is_file():
        print(f"no summary at {path}", file=sys.stderr)
        return 2

    md = path.read_text()
    items = headings(md, args.depth)
    block = render(items)

    if args.check:
        current = md.split(BEGIN, 1)[1].split(END, 1)[0] if BEGIN in md and END in md else None
        if current is None:
            print(f"{path.name}: no contents block")
            return 1
        stale = current.strip() != block[len(BEGIN):-len(END)].strip()
        print(f"{path.name}: contents {'STALE — re-run without --check' if stale else 'current'}")
        return 1 if stale else 0

    path.write_text(splice(md, block))
    by_level: dict[int, int] = {}
    for level, _t, _a in items:
        by_level[level] = by_level.get(level, 0) + 1
    print(f"{path.name}: {len(items)} entries · " + " · ".join(f"h{k} {v}" for k, v in sorted(by_level.items())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
